using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.FormKeys.Fallout4;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using Noggog;

namespace FO4FalloutGeneticsPatch
{
    public class Program
    {
        private static Lazy<Settings> _settings;
        private static Settings Settings => _settings.Value;

        private static readonly StringBuilder DebugLog = new StringBuilder();

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.Fallout4, "FalloutGenetics_Patch.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<IFallout4Mod, IFallout4ModGetter> state)
        {
            var female = new GenderRecord();
            var male = new GenderRecord();
            var neutral = new GenderRecord();

            Log($"=== Fallout Genetics diagnostic run {DateTime.Now:yyyy-MM-dd HH:mm:ss} ===");

            foreach (var hdptContext in state.LoadOrder.PriorityOrder.HeadPart().WinningContextOverrides())
            {
                var record = hdptContext.Record;
                if (record is null) continue;
                if (record.IsDeleted) continue;
                if (record.MajorFlags.HasFlag(HeadPart.MajorFlag.NonPlayable)) continue;

                if (record.ValidRaces.IsNull) continue;
                if (!record.ValidRaces.FormKey.Equals(Fallout4.FormList.HeadPartsGhouls.FormKey) &&
                    !record.ValidRaces.FormKey.Equals(Fallout4.FormList.HeadPartsHuman.FormKey) &&
                    !record.ValidRaces.FormKey.Equals(Fallout4.FormList.HeadPartsHumanGhouls.FormKey))
                    continue;

                if ((record.Flags.HasFlag(HeadPart.Flag.Female) && record.Flags.HasFlag(HeadPart.Flag.Male)) ||
                    (!record.Flags.HasFlag(HeadPart.Flag.Female) && !record.Flags.HasFlag(HeadPart.Flag.Male)))
                {
                    switch (record.Type)
                    {
                        case HeadPart.TypeEnum.Eyes:
                            neutral.Eyes.Add(record);
                            break;
                        case HeadPart.TypeEnum.Hair:
                            neutral.Hair.Add(record);
                            break;
                        case HeadPart.TypeEnum.FacialHair:
                            if (IsLikelyTopLevelFacialHair(record))
                                neutral.FacialHair.Add(record);
                            break;
                        case HeadPart.TypeEnum.Scars:
                            neutral.Scar.Add(record);
                            break;
                        case HeadPart.TypeEnum.Eyebrows:
                            neutral.Brows.Add(record);
                            break;
                    }
                }
                else if (record.Flags.HasFlag(HeadPart.Flag.Female))
                {
                    switch (record.Type)
                    {
                        case HeadPart.TypeEnum.Eyes:
                            female.Eyes.Add(record);
                            break;
                        case HeadPart.TypeEnum.Hair:
                            female.Hair.Add(record);
                            break;
                        case HeadPart.TypeEnum.Scars:
                            female.Scar.Add(record);
                            break;
                        case HeadPart.TypeEnum.Eyebrows:
                            female.Brows.Add(record);
                            break;
                    }
                }
                else if (record.Flags.HasFlag(HeadPart.Flag.Male))
                {
                    switch (record.Type)
                    {
                        case HeadPart.TypeEnum.Eyes:
                            male.Eyes.Add(record);
                            break;
                        case HeadPart.TypeEnum.Hair:
                            male.Hair.Add(record);
                            break;
                        case HeadPart.TypeEnum.FacialHair:
                            if (IsLikelyTopLevelFacialHair(record))
                                male.FacialHair.Add(record);
                            break;
                        case HeadPart.TypeEnum.Scars:
                            male.Scar.Add(record);
                            break;
                        case HeadPart.TypeEnum.Eyebrows:
                            male.Brows.Add(record);
                            break;
                    }
                }
            }

            Console.WriteLine(
                $"Neutral headparts:\n\tEyes - {neutral.Eyes.Count}\n\tHair - {neutral.Hair.Count}\n\tEyebrows - {neutral.Brows.Count}\n\tScars - {neutral.Scar.Count}\n\tFacial Hair - {neutral.FacialHair.Count}");
            Console.WriteLine(
                $"Female headparts:\n\tEyes - {female.Eyes.Count}\n\tHair - {female.Hair.Count}\n\tEyebrows - {female.Brows.Count}\n\tScars - {female.Scar.Count}");
            Console.WriteLine(
                $"Male headparts:\n\tEyes - {male.Eyes.Count}\n\tHair - {male.Hair.Count}\n\tEyebrows - {male.Brows.Count}\n\tScars - {male.Scar.Count}\n\tFacial Hair - {male.FacialHair.Count}");

            Log($"Pools:");
            Log($"Neutral Eyes={neutral.Eyes.Count}, Hair={neutral.Hair.Count}, Brows={neutral.Brows.Count}, Scars={neutral.Scar.Count}, FacialHair={neutral.FacialHair.Count}");
            Log($"Female Eyes={female.Eyes.Count}, Hair={female.Hair.Count}, Brows={female.Brows.Count}, Scars={female.Scar.Count}");
            Log($"Male Eyes={male.Eyes.Count}, Hair={male.Hair.Count}, Brows={male.Brows.Count}, Scars={male.Scar.Count}, FacialHair={male.FacialHair.Count}");

            male.Eyes.AddRange(neutral.Eyes);
            male.Hair.AddRange(neutral.Hair);
            male.FacialHair.AddRange(neutral.FacialHair);
            male.Scar.AddRange(neutral.Scar);
            male.Brows.AddRange(neutral.Brows);

            female.Eyes.AddRange(neutral.Eyes);
            female.Hair.AddRange(neutral.Hair);
            female.Scar.AddRange(neutral.Scar);
            female.Brows.AddRange(neutral.Brows);

            male.DefaultPreset.Add(Fallout4.HeadPart.MaleHeadHuman.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleHeadHumanRearTEMP.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleEyesHumanLashes.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleMouthHumanoidDefault.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleEyesHumanAO.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleEyesHumanWet.FormKey);

            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleHeadHuman.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleHeadHumanRearTEMP.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleEyesHumanLashes.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleMouthHumanoidDefault.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleEyesHumanAO.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleEyesHumanWet.FormKey);

            Random random = new Random(Guid.NewGuid().GetHashCode());

            var presetPath = Path.Combine(state.DataFolderPath, "F4SE\\Plugins\\F4EE\\Presets\\falloutGenetics");
            foreach (var file in Directory.EnumerateFiles(presetPath, "*.json", SearchOption.TopDirectoryOnly))
            {
                var preset = JsonConvert.DeserializeObject<Preset>(File.ReadAllText(file));
                if (preset is null) continue;

                if (preset.Morphs.Values is null)
                    preset.Morphs.Values = new List<double> { 0, 0, 0, 0, 0 };

                if (preset.Gender == 1)
                    female.Presets.Add(preset);
                else
                    male.Presets.Add(preset);
            }

            Console.WriteLine($"Found {female.Presets.Count} female presets and {male.Presets.Count} male presets.");
            Log($"Presets: female={female.Presets.Count}, male={male.Presets.Count}");

            int inspected = 0;

            foreach (var npcContext in state.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
            {
                var record = npcContext.Record;
                if (record is null) continue;
                if (record.IsDeleted) continue;
                if (record.Race.IsNull || !record.Race.FormKey.Equals(Fallout4.Race.HumanRace.FormKey)) continue;

                var newRecord = npcContext.GetOrAddAsOverride(state.PatchMod);

                var finalParts = GetPreservedExistingNonGeneratedParts(record, state.LinkCache);

                var presets = new List<Preset>();

                bool useFemaleParts =
                    (record.Flags.HasFlag(Npc.Flag.Female) && Settings.FemaleParts == PartGenderType.Female) ||
                    (!record.Flags.HasFlag(Npc.Flag.Female) && Settings.MaleParts == PartGenderType.Female);

                bool doLogNpc = inspected < 20;
                if (doLogNpc)
                {
                    inspected++;
                    Log("");
                    Log($"NPC {inspected}: {DescribeNpc(record)}");
                    Log($"Existing preserved non-generated parts: {string.Join(", ", finalParts.Select(f => f.ToString()))}");
                }

                if (useFemaleParts)
                {
                    AddMissingDefaults(finalParts, female.DefaultPreset, doLogNpc ? "female defaults" : null);
                    AddRandomSimplePart(finalParts, female.Eyes, random, doLogNpc ? "female eyes" : null);
                    AddRandomBundledPartDirectOnly(finalParts, female.Hair, random, doLogNpc ? "female hair" : null);
                    AddRandomSimplePart(finalParts, female.Brows, random, doLogNpc ? "female brows" : null);
                    AddRandomSimplePart(finalParts, female.Scar, random, doLogNpc ? "female scars" : null);
                    presets = female.Presets;
                }
                else
                {
                    AddMissingDefaults(finalParts, male.DefaultPreset, doLogNpc ? "male defaults" : null);
                    AddRandomSimplePart(finalParts, male.Eyes, random, doLogNpc ? "male eyes" : null);
                    AddRandomBundledPartDirectOnly(finalParts, male.Hair, random, doLogNpc ? "male hair" : null);
                    AddRandomSimplePart(finalParts, male.Brows, random, doLogNpc ? "male brows" : null);
                    AddRandomSimplePart(finalParts, male.Scar, random, doLogNpc ? "male scars" : null);
                    AddRandomBundledPartDirectOnly(finalParts, male.FacialHair, random, doLogNpc ? "male facial hair" : null);
                    presets = male.Presets;
                }

                if (doLogNpc)
                {
                    Log($"Final HeadParts to write ({finalParts.Count}):");
                    foreach (var fk in finalParts)
                    {
                        Log($"  -> {DescribeHeadPartFormKey(fk, state.LinkCache)}");
                    }
                }

                newRecord.HeadParts.Clear();
                newRecord.HeadParts.AddRange(finalParts);

                if (Settings.UseMorphs && presets.Count > 0)
                {
                    var p1 = presets[random.Next(presets.Count)];
                    var p2 = presets[random.Next(presets.Count)];

                    var child = Genetics(p1.Morphs, p2.Morphs, random.NextDouble());
                    Morph(newRecord, child);
                }
            }

            var logPath = Path.Combine(state.DataFolderPath, "FalloutGenetics_debug_log.txt");
            File.WriteAllText(logPath, DebugLog.ToString());
            Console.WriteLine($"Diagnostic log written to: {logPath}");
        }

        private static List<FormKey> GetPreservedExistingNonGeneratedParts(
            INpcGetter npc,
            ILinkCache<IFallout4Mod, IFallout4ModGetter> linkCache)
        {
            var result = new List<FormKey>();
            if (npc.HeadParts is null) return result;

            foreach (var hp in npc.HeadParts)
            {
                if (hp.IsNull) continue;

                if (!linkCache.TryResolve<IHeadPartGetter>(hp.FormKey, out var resolved) || resolved is null)
                {
                    AddUnique(result, hp.FormKey);
                    continue;
                }

                if (resolved.Type == HeadPart.TypeEnum.Eyes ||
                    resolved.Type == HeadPart.TypeEnum.Hair ||
                    resolved.Type == HeadPart.TypeEnum.FacialHair ||
                    resolved.Type == HeadPart.TypeEnum.Eyebrows ||
                    resolved.Type == HeadPart.TypeEnum.Scars)
                {
                    continue;
                }

                AddUnique(result, hp.FormKey);
            }

            return result;
        }

        private static void AddMissingDefaults(List<FormKey> target, IEnumerable<FormKey> defaults, string? label)
        {
            foreach (var fk in defaults)
            {
                AddUnique(target, fk);
            }

            if (!string.IsNullOrWhiteSpace(label))
                Log($"Added/ensured {label}");
        }

        private static void AddRandomSimplePart(
            List<FormKey> target,
            List<IHeadPartGetter> source,
            Random random,
            string? label)
        {
            if (source.Count == 0)
            {
                if (!string.IsNullOrWhiteSpace(label))
                    Log($"{label}: pool empty");
                return;
            }

            var chosen = source[random.Next(source.Count)];
            if (chosen is null)
            {
                if (!string.IsNullOrWhiteSpace(label))
                    Log($"{label}: chosen null");
                return;
            }

            AddUnique(target, chosen.FormKey);

            if (!string.IsNullOrWhiteSpace(label))
                Log($"{label}: chose {DescribeHeadPart(chosen)}");
        }

        private static void AddRandomBundledPartDirectOnly(
            List<FormKey> target,
            List<IHeadPartGetter> source,
            Random random,
            string? label)
        {
            if (source.Count == 0)
            {
                if (!string.IsNullOrWhiteSpace(label))
                    Log($"{label}: pool empty");
                return;
            }

            var chosen = source[random.Next(source.Count)];
            if (chosen is null)
            {
                if (!string.IsNullOrWhiteSpace(label))
                    Log($"{label}: chosen null");
                return;
            }

            AddDirectBundle(target, chosen, label);
        }

        private static void AddDirectBundle(
            List<FormKey> target,
            IHeadPartGetter chosen,
            string? label)
        {
            AddUnique(target, chosen.FormKey);

            if (!string.IsNullOrWhiteSpace(label))
            {
                Log($"{label}: parent {DescribeHeadPart(chosen)}");
                Log($"{label}: direct ExtraParts count = {chosen.ExtraParts?.Count ?? 0}");
            }

            if (chosen.ExtraParts is null) return;

            int i = 0;
            foreach (var extra in chosen.ExtraParts)
            {
                if (extra.IsNull) continue;
                AddUnique(target, extra.FormKey);

                if (!string.IsNullOrWhiteSpace(label))
                {
                    i++;
                    Log($"{label}: extra {i} -> {extra.FormKey}");
                }
            }
        }

        private static void AddUnique(List<FormKey> target, FormKey fk)
        {
            foreach (var existing in target)
            {
                if (existing.Equals(fk))
                    return;
            }

            target.Add(fk);
        }

        private static bool IsLikelyTopLevelFacialHair(IHeadPartGetter part)
        {
            if (part.Type != HeadPart.TypeEnum.FacialHair) return false;

            var edid = part.EditorID ?? string.Empty;
            var full = part.Name?.String ?? string.Empty;

            if (edid.StartsWith("Part", StringComparison.OrdinalIgnoreCase)) return false;
            if (edid.Contains("Hairline", StringComparison.OrdinalIgnoreCase)) return false;
            if (full.Contains("Part ", StringComparison.OrdinalIgnoreCase)) return false;
            if (full.Contains("Hairline", StringComparison.OrdinalIgnoreCase)) return false;

            return true;
        }

        private static string DescribeNpc(INpcGetter npc)
        {
            string edid = npc.EditorID ?? "<no EDID>";
            return $"{edid} [{npc.FormKey}] Female={npc.Flags.HasFlag(Npc.Flag.Female)}";
        }

        private static string DescribeHeadPart(IHeadPartGetter hp)
        {
            string edid = hp.EditorID ?? "<no EDID>";
            string name = hp.Name?.String ?? "<no name>";
            return $"{edid} | {name} | {hp.Type} | [{hp.FormKey}]";
        }

        private static string DescribeHeadPartFormKey(FormKey fk, ILinkCache<IFallout4Mod, IFallout4ModGetter> linkCache)
        {
            if (!linkCache.TryResolve<IHeadPartGetter>(fk, out var hp) || hp is null)
                return fk.ToString();

            return DescribeHeadPart(hp);
        }

        private static void Log(string text) => DebugLog.AppendLine(text);

        private static PresetMorph Genetics(PresetMorph p1, PresetMorph p2, double t)
        {
            p1.Values ??= new List<double> { 0, 0, 0, 0, 0 };
            p2.Values ??= new List<double> { 0, 0, 0, 0, 0 };
            var child = new PresetMorph
            {
                Presets = ConvolvePresets(p1.Presets, p2.Presets, t),
                Regions = ConvolveRegions(p1.Regions, p2.Regions, t),
                Values = Combine(p1.Values, p2.Values, t)
            };
            return child;
        }

        private static List<double> Combine(List<double> a, List<double> b, double t)
        {
            var c = new List<double>();
            for (var i = 0; i < Math.Min(a.Count, b.Count); i++)
                c.Add(t * a[i] + (1 - t) * b[i]);
            return c;
        }

        private static Dictionary<string, List<double>> ConvolveRegions(
            Dictionary<string, List<double>> x,
            Dictionary<string, List<double>> y,
            double t)
        {
            var child = new Dictionary<string, List<double>>();
            foreach (var i in x.Keys)
            {
                var yi = new List<double> { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
                if (y.ContainsKey(i)) yi = y[i];
                child.Add(i, Combine(x[i], yi, t));
            }

            foreach (var i in y.Keys)
            {
                var xi = new List<double> { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
                if (x.ContainsKey(i)) continue;
                child.Add(i, Combine(xi, y[i], t));
            }

            return child;
        }

        private static Dictionary<string, double> ConvolvePresets(
            Dictionary<string, double> x,
            Dictionary<string, double> y,
            double t)
        {
            var child = new Dictionary<string, double>();
            foreach (var i in x.Keys)
            {
                var yi = 0.0;
                if (y.ContainsKey(i)) yi = y[i];
                child.Add(i, t * x[i] + (1 - t) * yi);
            }

            foreach (var i in y.Keys)
            {
                if (x.ContainsKey(i)) continue;
                child.Add(i, (1 - t) * y[i]);
            }

            return child;
        }

        private static void Morph(INpc r, PresetMorph p)
        {
            r.FaceMorphs.Clear();
            var reg = p.Regions;
            foreach (var pt in reg.Keys)
            {
                var fm = new NpcFaceMorph
                {
                    Index = uint.Parse(pt, System.Globalization.NumberStyles.HexNumber),
                    Position = new P3Float((float)reg[pt][0], (float)reg[pt][1], (float)reg[pt][2]),
                    Rotation = new P3Float((float)reg[pt][3], (float)reg[pt][4], (float)reg[pt][5]),
                    Scale = (float)reg[pt][6]
                };
                r.FaceMorphs.Add(fm);
            }

            var c = p.Presets;
            r.Morphs.Clear();
            foreach (var pt in c.Keys)
            {
                var m = new NpcMorph
                {
                    Key = uint.Parse(pt, System.Globalization.NumberStyles.HexNumber),
                    Value = (float)c[pt]
                };
                r.Morphs.Add(m);
            }

            var bm = p.Values;
            r.BodyMorphRegionValues = new NpcBodyMorphRegionValues
            {
                Head = (float)bm[0],
                UpperTorso = (float)bm[1],
                Arms = (float)bm[2],
                LowerTorso = (float)bm[3],
                Legs = (float)bm[4]
            };
            r.FacialMorphIntensity = null;
        }
    }
}
