using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.FormKeys.Fallout4;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using Noggog;

namespace FO4FalloutGeneticsPatch
{
    public class Program
    {
        private static Lazy<Settings> _settings;
        private static Settings Settings => _settings.Value;

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.Fallout4, "FalloutGenetics_Patch.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<IFallout4Mod, IFallout4ModGetter> state)
        {
            var female = new GenderRecord();
            var male = new GenderRecord();
            var neutral = new GenderRecord();

            var directExtrasByParent = new Dictionary<FormKey, List<FormKey>>();
            var generatedBundleChildParts = new HashSet<FormKey>();
            var deletedHeadParts = new HashSet<FormKey>();

            // Pass 1:
            // Track deleted headparts and precompute direct extras.
            foreach (var ctx in state.LoadOrder.PriorityOrder.HeadPart().WinningContextOverrides())
            {
                var rec = ctx.Record;
                if (rec == null) continue;

                if (rec.IsDeleted)
                {
                    deletedHeadParts.Add(rec.FormKey);
                    continue;
                }

                var extras = new List<FormKey>();

                if (rec.ExtraParts != null)
                {
                    foreach (var extra in rec.ExtraParts)
                    {
                        if (extra.IsNull) continue;
                        if (deletedHeadParts.Contains(extra.FormKey)) continue;

                        extras.Add(extra.FormKey);

                        if (rec.Type == HeadPart.TypeEnum.Hair ||
                            rec.Type == HeadPart.TypeEnum.FacialHair)
                        {
                            generatedBundleChildParts.Add(extra.FormKey);
                        }
                    }
                }

                directExtrasByParent[rec.FormKey] = extras;
            }

            // Pass 2:
            // Build randomized pools from all playable headparts.
            foreach (var ctx in state.LoadOrder.PriorityOrder.HeadPart().WinningContextOverrides())
            {
                var rec = ctx.Record;
                if (rec == null) continue;
                if (rec.IsDeleted) continue;
                if (rec.MajorFlags.HasFlag(HeadPart.MajorFlag.NonPlayable)) continue;

                bool femaleFlag = rec.Flags.HasFlag(HeadPart.Flag.Female);
                bool maleFlag = rec.Flags.HasFlag(HeadPart.Flag.Male);

                void AddTo(GenderRecord g)
                {
                    switch (rec.Type)
                    {
                        case HeadPart.TypeEnum.Eyes:
                            g.Eyes.Add(rec);
                            break;
                        case HeadPart.TypeEnum.Hair:
                            g.Hair.Add(rec);
                            break;
                        case HeadPart.TypeEnum.Scars:
                            g.Scar.Add(rec);
                            break;
                        case HeadPart.TypeEnum.Eyebrows:
                            g.Brows.Add(rec);
                            break;
                        case HeadPart.TypeEnum.FacialHair:
                            if (IsLikelyTopLevelFacialHair(rec))
                                g.FacialHair.Add(rec);
                            break;
                    }
                }

                if ((femaleFlag && maleFlag) || (!femaleFlag && !maleFlag))
                    AddTo(neutral);
                else if (femaleFlag)
                    AddTo(female);
                else if (maleFlag)
                    AddTo(male);
            }

            Console.WriteLine(
                $"Neutral headparts:\n\tEyes - {neutral.Eyes.Count}\n\tHair - {neutral.Hair.Count}\n\tEyebrows - {neutral.Brows.Count}\n\tScars - {neutral.Scar.Count}\n\tFacial Hair - {neutral.FacialHair.Count}");
            Console.WriteLine(
                $"Female headparts:\n\tEyes - {female.Eyes.Count}\n\tHair - {female.Hair.Count}\n\tEyebrows - {female.Brows.Count}\n\tScars - {female.Scar.Count}");
            Console.WriteLine(
                $"Male headparts:\n\tEyes - {male.Eyes.Count}\n\tHair - {male.Hair.Count}\n\tEyebrows - {male.Brows.Count}\n\tScars - {male.Scar.Count}\n\tFacial Hair - {male.FacialHair.Count}");

            male.Eyes.AddRange(neutral.Eyes);
            male.Hair.AddRange(neutral.Hair);
            male.FacialHair.AddRange(neutral.FacialHair);
            male.Scar.AddRange(neutral.Scar);
            male.Brows.AddRange(neutral.Brows);

            female.Eyes.AddRange(neutral.Eyes);
            female.Hair.AddRange(neutral.Hair);
            female.Scar.AddRange(neutral.Scar);
            female.Brows.AddRange(neutral.Brows);

            male.DefaultPreset.Add(Fallout4.HeadPart.MaleHeadHuman.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleHeadHumanRearTEMP.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleEyesHumanLashes.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleMouthHumanoidDefault.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleEyesHumanAO.FormKey);
            male.DefaultPreset.Add(Fallout4.HeadPart.MaleEyesHumanWet.FormKey);

            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleHeadHuman.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleHeadHumanRearTEMP.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleEyesHumanLashes.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleMouthHumanoidDefault.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleEyesHumanAO.FormKey);
            female.DefaultPreset.Add(Fallout4.HeadPart.FemaleEyesHumanWet.FormKey);

            // Presets may still be loaded for future use, but morphs are disabled below.
            var presetPath = Path.Combine(state.DataFolderPath, "F4SE\\Plugins\\F4EE\\Presets\\falloutGenetics");
            foreach (var file in Directory.EnumerateFiles(presetPath, "*.json", SearchOption.TopDirectoryOnly))
            {
                var preset = JsonConvert.DeserializeObject<Preset>(File.ReadAllText(file));
                if (preset == null) continue;

                if (preset.Morphs.Values == null)
                    preset.Morphs.Values = new List<double> { 0, 0, 0, 0, 0 };

                if (preset.Gender == 1)
                    female.Presets.Add(preset);
                else
                    male.Presets.Add(preset);
            }

            Console.WriteLine($"Found {female.Presets.Count} female presets and {male.Presets.Count} male presets.");
            Console.WriteLine("Morph application is disabled in this build.");

            var rand = new Random();

            foreach (var npcCtx in state.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
            {
                var npc = npcCtx.Record;
                if (npc == null || npc.IsDeleted) continue;
                if (npc.Race.IsNull || !npc.Race.FormKey.Equals(Fallout4.Race.HumanRace.FormKey)) continue;

                var newNpc = npcCtx.GetOrAddAsOverride(state.PatchMod);

                var parts = GetPreservedExistingNonGeneratedParts(
                    npc,
                    state.LinkCache,
                    generatedBundleChildParts,
                    deletedHeadParts);

                var isFemale = npc.Flags.HasFlag(Npc.Flag.Female);
                var pool = isFemale ? female : male;

                AddMissingDefaults(parts, isFemale ? female.DefaultPreset : male.DefaultPreset);

                AddRandom(parts, pool.Eyes, rand);
                AddRandomBundle(parts, pool.Hair, rand, directExtrasByParent, deletedHeadParts);
                AddRandom(parts, pool.Brows, rand);
                AddRandom(parts, pool.Scar, rand);

                if (!isFemale)
                    AddRandomBundle(parts, pool.FacialHair, rand, directExtrasByParent, deletedHeadParts);

                newNpc.HeadParts.Clear();
                newNpc.HeadParts.AddRange(parts);

                // Morphs intentionally disabled.
                // Existing FMIN / FacialMorphIntensity is preserved because we do not touch it.
            }
        }

        private static void AddRandom(List<FormKey> target, List<IHeadPartGetter> pool, Random rand)
        {
            if (pool.Count == 0) return;
            AddUnique(target, pool[rand.Next(pool.Count)].FormKey);
        }

        private static void AddRandomBundle(
            List<FormKey> target,
            List<IHeadPartGetter> pool,
            Random rand,
            Dictionary<FormKey, List<FormKey>> extras,
            HashSet<FormKey> deletedHeadParts)
        {
            if (pool.Count == 0) return;

            var chosen = pool[rand.Next(pool.Count)];
            AddUnique(target, chosen.FormKey);

            if (!extras.TryGetValue(chosen.FormKey, out var ex)) return;

            foreach (var e in ex)
            {
                if (deletedHeadParts.Contains(e))
                    continue;

                AddUnique(target, e);
            }
        }

        private static List<FormKey> GetPreservedExistingNonGeneratedParts(
            INpcGetter npc,
            ILinkCache<IFallout4Mod, IFallout4ModGetter> cache,
            HashSet<FormKey> generatedChildren,
            HashSet<FormKey> deletedHeadParts)
        {
            var result = new List<FormKey>();

            if (npc.HeadParts == null) return result;

            foreach (var hp in npc.HeadParts)
            {
                if (hp.IsNull) continue;

                // Drop anything whose winning record is deleted.
                if (deletedHeadParts.Contains(hp.FormKey))
                    continue;

                // Drop stale old bundle children.
                if (generatedChildren.Contains(hp.FormKey))
                    continue;

                if (!cache.TryResolve<IHeadPartGetter>(hp.FormKey, out var rec) || rec == null)
                {
                    AddUnique(result, hp.FormKey);
                    continue;
                }

                if (rec.IsDeleted)
                    continue;

                if (rec.Type == HeadPart.TypeEnum.Eyes ||
                    rec.Type == HeadPart.TypeEnum.Hair ||
                    rec.Type == HeadPart.TypeEnum.FacialHair ||
                    rec.Type == HeadPart.TypeEnum.Eyebrows ||
                    rec.Type == HeadPart.TypeEnum.Scars)
                {
                    continue;
                }

                AddUnique(result, hp.FormKey);
            }

            return result;
        }

        private static void AddMissingDefaults(List<FormKey> target, IEnumerable<FormKey> defaults)
        {
            foreach (var fk in defaults)
                AddUnique(target, fk);
        }

        private static void AddUnique(List<FormKey> list, FormKey fk)
        {
            if (!list.Contains(fk))
                list.Add(fk);
        }

        private static bool IsLikelyTopLevelFacialHair(IHeadPartGetter part)
        {
            if (part.Type != HeadPart.TypeEnum.FacialHair) return false;

            var edid = part.EditorID ?? "";
            var name = part.Name?.String ?? "";

            if (edid.StartsWith("Part", StringComparison.OrdinalIgnoreCase)) return false;
            if (edid.Contains("Hairline", StringComparison.OrdinalIgnoreCase)) return false;
            if (name.Contains("Part ", StringComparison.OrdinalIgnoreCase)) return false;
            if (name.Contains("Hairline", StringComparison.OrdinalIgnoreCase)) return false;

            return true;
        }

        // Left in place so the file still compiles cleanly with your existing model types,
        // but unused in this build because morph application is disabled.
        private static PresetMorph Genetics(PresetMorph p1, PresetMorph p2, double t)
        {
            p1.Values ??= new List<double> { 0, 0, 0, 0, 0 };
            p2.Values ??= new List<double> { 0, 0, 0, 0, 0 };
            var child = new PresetMorph
            {
                Presets = ConvolvePresets(p1.Presets, p2.Presets, t),
                Regions = ConvolveRegions(p1.Regions, p2.Regions, t),
                Values = Combine(p1.Values, p2.Values, t)
            };
            return child;
        }

        private static List<double> Combine(List<double> a, List<double> b, double t)
        {
            var c = new List<double>();
            for (var i = 0; i < Math.Min(a.Count, b.Count); i++)
                c.Add(t * a[i] + (1 - t) * b[i]);
            return c;
        }

        private static Dictionary<string, List<double>> ConvolveRegions(
            Dictionary<string, List<double>> x,
            Dictionary<string, List<double>> y,
            double t)
        {
            var child = new Dictionary<string, List<double>>();
            foreach (var i in x.Keys)
            {
                var yi = new List<double> { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
                if (y.ContainsKey(i)) yi = y[i];
                child.Add(i, Combine(x[i], yi, t));
            }

            foreach (var i in y.Keys)
            {
                var xi = new List<double> { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
                if (x.ContainsKey(i)) continue;
                child.Add(i, Combine(xi, y[i], t));
            }

            return child;
        }

        private static Dictionary<string, double> ConvolvePresets(
            Dictionary<string, double> x,
            Dictionary<string, double> y,
            double t)
        {
            var child = new Dictionary<string, double>();
            foreach (var i in x.Keys)
            {
                var yi = 0.0;
                if (y.ContainsKey(i)) yi = y[i];
                child.Add(i, t * x[i] + (1 - t) * yi);
            }

            foreach (var i in y.Keys)
            {
                if (x.ContainsKey(i)) continue;
                child.Add(i, (1 - t) * y[i]);
            }

            return child;
        }

        private static void Morph(INpc r, PresetMorph p)
        {
            r.FaceMorphs.Clear();
            var reg = p.Regions;
            foreach (var pt in reg.Keys)
            {
                var fm = new NpcFaceMorph
                {
                    Index = uint.Parse(pt, System.Globalization.NumberStyles.HexNumber),
                    Position = new P3Float((float)reg[pt][0], (float)reg[pt][1], (float)reg[pt][2]),
                    Rotation = new P3Float((float)reg[pt][3], (float)reg[pt][4], (float)reg[pt][5]),
                    Scale = (float)reg[pt][6]
                };
                r.FaceMorphs.Add(fm);
            }

            var c = p.Presets;
            r.Morphs.Clear();
            foreach (var pt in c.Keys)
            {
                var m = new NpcMorph
                {
                    Key = uint.Parse(pt, System.Globalization.NumberStyles.HexNumber),
                    Value = (float)c[pt]
                };
                r.Morphs.Add(m);
            }

            var bm = p.Values;
            r.BodyMorphRegionValues = new NpcBodyMorphRegionValues
            {
                Head = (float)bm[0],
                UpperTorso = (float)bm[1],
                Arms = (float)bm[2],
                LowerTorso = (float)bm[3],
                Legs = (float)bm[4]
            };

            // Preserve existing FMIN / FacialMorphIntensity if present.
        }
    }
}
