using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.FormKeys.Fallout4;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using Noggog;

namespace FO4FalloutGeneticsPatch
{
    public class Program
    {
        private static Lazy<Settings> _settings;
        private static Settings Settings => _settings.Value;

        private static HashSet<ModKey> AllowedMods = new();

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.Fallout4, "FalloutGenetics_Patch.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<IFallout4Mod, IFallout4ModGetter> state)
        {
            AllowedMods = Settings.AllowedHeadPartMods
                .Select(x => ModKey.FromNameAndExtension(x))
                .ToHashSet();

            var female = new GenderRecord();
            var male = new GenderRecord();
            var neutral = new GenderRecord();

            var directExtrasByParent = new Dictionary<FormKey, List<FormKey>>();
            var generatedBundleChildParts = new HashSet<FormKey>();
            var deletedHeadParts = new HashSet<FormKey>();

            foreach (var ctx in state.LoadOrder.PriorityOrder.HeadPart().WinningContextOverrides())
            {
                var rec = ctx.Record;
                if (rec == null) continue;

                if (rec.IsDeleted)
                {
                    deletedHeadParts.Add(rec.FormKey);
                    continue;
                }

                var extras = new List<FormKey>();

                if (rec.ExtraParts != null)
                {
                    foreach (var extra in rec.ExtraParts)
                    {
                        if (extra.IsNull) continue;
                        if (deletedHeadParts.Contains(extra.FormKey)) continue;

                        extras.Add(extra.FormKey);

                        if (rec.Type == HeadPart.TypeEnum.Hair ||
                            rec.Type == HeadPart.TypeEnum.FacialHair)
                        {
                            generatedBundleChildParts.Add(extra.FormKey);
                        }
                    }
                }

                directExtrasByParent[rec.FormKey] = extras;
            }

            foreach (var ctx in state.LoadOrder.PriorityOrder.HeadPart().WinningContextOverrides())
            {
                var rec = ctx.Record;
                if (rec == null || rec.IsDeleted) continue;
                if (rec.MajorFlags.HasFlag(HeadPart.MajorFlag.NonPlayable)) continue;
                if (!AllowedMods.Contains(rec.FormKey.ModKey)) continue;

                bool femaleFlag = rec.Flags.HasFlag(HeadPart.Flag.Female);
                bool maleFlag = rec.Flags.HasFlag(HeadPart.Flag.Male);

                void AddTo(GenderRecord g)
                {
                    switch (rec.Type)
                    {
                        case HeadPart.TypeEnum.Eyes: g.Eyes.Add(rec); break;
                        case HeadPart.TypeEnum.Hair: g.Hair.Add(rec); break;
                        case HeadPart.TypeEnum.Scars: g.Scar.Add(rec); break;
                        case HeadPart.TypeEnum.Eyebrows: g.Brows.Add(rec); break;
                        case HeadPart.TypeEnum.FacialHair:
                            if (IsLikelyTopLevelFacialHair(rec))
                                g.FacialHair.Add(rec);
                            break;
                    }
                }

                if ((femaleFlag && maleFlag) || (!femaleFlag && !maleFlag))
                    AddTo(neutral);
                else if (femaleFlag)
                    AddTo(female);
                else
                    AddTo(male);
            }

            male.Eyes.AddRange(neutral.Eyes);
            male.Hair.AddRange(neutral.Hair);
            male.FacialHair.AddRange(neutral.FacialHair);
            male.Scar.AddRange(neutral.Scar);
            male.Brows.AddRange(neutral.Brows);

            female.Eyes.AddRange(neutral.Eyes);
            female.Hair.AddRange(neutral.Hair);
            female.Scar.AddRange(neutral.Scar);
            female.Brows.AddRange(neutral.Brows);

            var rand = new Random();

            foreach (var npcCtx in state.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
            {
                var npc = npcCtx.Record;
                if (npc == null || npc.IsDeleted) continue;
                if (npc.Race.IsNull || !npc.Race.FormKey.Equals(Fallout4.Race.HumanRace.FormKey)) continue;

                var newNpc = npcCtx.GetOrAddAsOverride(state.PatchMod);

                var parts = GetPreservedExistingNonGeneratedParts(
                    npc,
                    state.LinkCache,
                    generatedBundleChildParts,
                    deletedHeadParts);

                var isFemale = npc.Flags.HasFlag(Npc.Flag.Female);
                var pool = isFemale ? female : male;

                AddRandom(parts, pool.Eyes, rand);
                AddRandomBundle(parts, pool.Hair, rand, directExtrasByParent, deletedHeadParts);
                AddRandom(parts, pool.Brows, rand);
                AddRandom(parts, pool.Scar, rand);

                if (!isFemale)
                    AddRandomBundle(parts, pool.FacialHair, rand, directExtrasByParent, deletedHeadParts);

                newNpc.HeadParts.Clear();
                newNpc.HeadParts.AddRange(parts);

                // 🚫 MORPHS DISABLED HERE (INTENTIONALLY REMOVED)
            }
        }

        private static void AddRandom(List<FormKey> target, List<IHeadPartGetter> pool, Random rand)
        {
            if (pool.Count == 0) return;
            AddUnique(target, pool[rand.Next(pool.Count)].FormKey);
        }

        private static void AddRandomBundle(
            List<FormKey> target,
            List<IHeadPartGetter> pool,
            Random rand,
            Dictionary<FormKey, List<FormKey>> extras,
            HashSet<FormKey> deletedHeadParts)
        {
            if (pool.Count == 0) return;

            var chosen = pool[rand.Next(pool.Count)];
            AddUnique(target, chosen.FormKey);

            if (!extras.TryGetValue(chosen.FormKey, out var ex)) return;

            foreach (var e in ex)
            {
                if (deletedHeadParts.Contains(e)) continue;
                AddUnique(target, e);
            }
        }

        private static List<FormKey> GetPreservedExistingNonGeneratedParts(
            INpcGetter npc,
            ILinkCache<IFallout4Mod, IFallout4ModGetter> cache,
            HashSet<FormKey> generatedChildren,
            HashSet<FormKey> deletedHeadParts)
        {
            var result = new List<FormKey>();
            if (npc.HeadParts == null) return result;

            foreach (var hp in npc.HeadParts)
            {
                if (hp.IsNull) continue;
                if (deletedHeadParts.Contains(hp.FormKey)) continue;
                if (generatedChildren.Contains(hp.FormKey)) continue;

                AddUnique(result, hp.FormKey);
            }

            return result;
        }

        private static void AddUnique(List<FormKey> list, FormKey fk)
        {
            if (!list.Contains(fk))
                list.Add(fk);
        }

        private static bool IsLikelyTopLevelFacialHair(IHeadPartGetter part)
        {
            if (part.Type != HeadPart.TypeEnum.FacialHair) return false;

            var edid = part.EditorID ?? "";
            var name = part.Name?.String ?? "";

            if (edid.StartsWith("Part", StringComparison.OrdinalIgnoreCase)) return false;
            if (edid.Contains("Hairline", StringComparison.OrdinalIgnoreCase)) return false;
            if (name.Contains("Part ", StringComparison.OrdinalIgnoreCase)) return false;
            if (name.Contains("Hairline", StringComparison.OrdinalIgnoreCase)) return false;

            return true;
        }
    }
}
